[%bibitem]
== {blank}
id:: ISOTC211
fetched:: 2020-10-08
title::
title.type:: title-main
title.content:: Geographic information
title.format:: text/plain
title::
title.type:: main
title.content:: Geographic information
title.format:: text/plain
title::
title.content:: Information géographique
title.language:: fr
title.script:: Latn
title.format:: text/plain
type:: standard
docid::
docid.type:: ISO
docid.id:: TC211
docid::
docid.type:: isbn
docid.id:: ISBN
docid::
docid.type:: lccn
docid.id:: LCCN
docid::
docid.type:: issn
docid.scope:: series
docid.id:: ISSN
docid::
docid.type:: URN
docid.id:: urn:iso:std:iso:123:stage-90.93:ed-3:en,fr
docnumber:: 123456
edition:: 1
language:: en
language:: fr
script:: Latn
version.revision_date:: 2019-04-01
version.draft:: draft
biblionote::
biblionote.content:: note
biblionote::
biblionote.content:: An note
biblionote::
biblionote.content:: How published
biblionote::
biblionote.content:: Comment
biblionote::
biblionote.content:: Table Of Contents
docstatus.stage:: 30
docstatus.substage:: substage
docstatus.iteration:: final
date::
date.type:: issued
date.on:: 2014-01-01
date::
date.type:: published
date.on:: 2014-04-01
date::
date.type:: accessed
date.on:: 2015-05-20
abstract::
abstract.content:: ISO 19115-1:2014 defines the schema required for ...
abstract.language:: en
abstract.script:: Latn
abstract.format:: text/plain
abstract::
abstract.content:: L'ISO 19115-1:2014 définit le schéma requis pour ...
abstract.language:: fr
abstract.script:: Latn
abstract.format:: text/plain
copyright.owner.name.content:: International Organization for Standardization
copyright.owner.abbreviation.content:: ISO
copyright.owner.url:: www.iso.org
copyright.role.type:: publisher
copyright.from:: 2014
copyright.to:: 2020
copyright.scope:: Scope
link::
link.type:: src
link.content:: https://www.iso.org/standard/53798.html
link::
link.type:: obp
link.content:: https://www.iso.org/obp/ui/#!iso:std:53798:en
link::
link.type:: rss
link.content:: https://www.iso.org/contents/data/standard/05/37/53798.detail.rss
link::
link.type:: doi
link.content:: http://standrd.org/doi-123
link::
link.type:: file
link.content:: file://path/file
medium.form:: medium form
medium.size:: medium size
medium.scale:: medium scale
place::
place.name:: bib place
place::
place.name:: Geneva
place.uri:: geneva.place
place.region:: Switzelznd
extent::
extent.type:: section
extent.reference_from:: Reference from
extent.reference_to:: Reference to
extent::
extent.type:: chapter
extent.reference_from:: 4
extent::
extent.type:: page
extent.reference_from:: 10
extent.reference_to:: 20
extent::
extent.type:: volume
extent.reference_from:: 1
accesslocation:: accesslocation1
accesslocation:: accesslocation2
classification::
classification.type:: type
classification.value:: value
classification::
classification.type:: keyword
classification.value:: Keywords
classification::
classification.type:: mendeley
classification.value:: Mendeley Tags
validity.begins:: 2010-10-10 12:21
validity.ends:: 2011-02-03 18:30
validity.revision:: 2011-03-04 09:00
contributor::
contributor.organization.name.content:: International Organization for Standardization
contributor.organization.abbreviation.content:: ISO
contributor.organization.subdivision.content:: division
contributor.organization.url:: www.iso.org
contributor.role.description.content:: Publisher role
contributor.role.type:: publisher
contributor::
contributor.person.name.completename.content:: A. Bierman
contributor.person.name.completename.language:: en
contributor.person.affiliation.organization.name.content:: IETF
contributor.person.affiliation.organization.abbreviation.content:: IETF
contributor.person.affiliation.organization.identifier.type:: uri
contributor.person.affiliation.organization.identifier.value:: www.ietf.org
contributor.person.address.street:: Street
contributor.person.address.city:: City
contributor.person.address.state:: State
contributor.person.address.country:: Country
contributor.person.address.postcode:: 123456
contributor.person.contact.type:: phone
contributor.person.contact.value:: 223322
contributor.role.type:: author
contributor::
contributor.organization.name.content:: IETF
contributor.organization.abbreviation.content:: IETF
contributor.organization.identifier.type:: uri
contributor.organization.identifier.value:: www.ietf.org
contributor::
contributor.role.description.content:: Publisher description
contributor.role.type:: publisher
contributor::
contributor.role.description.content:: Editor description
contributor.role.type:: editor
contributor::
contributor.person.name.forename.content:: Forename
contributor.person.name.forename.language:: en
contributor.person.name.initial.content:: A.
contributor.person.name.initial.language:: en
contributor.person.name.surname.content:: Bierman
contributor.person.name.surname.language:: en
contributor.person.name.addition.content:: Addition
contributor.person.name.addition.language:: en
contributor.person.name.prefix.content:: Prefix
contributor.person.name.prefix.language:: en
contributor.person.affiliation.description.content:: Description
contributor.person.affiliation.description.language:: en
contributor.person.affiliation.organization.name.content:: IETF
contributor.person.affiliation.organization.abbreviation.content:: IETF
contributor.person.type:: uri
contributor.person.value:: www.person.com
contributor.person.address.street:: Street
contributor.person.address.city:: City
contributor.person.address.state:: State
contributor.person.address.country:: Country
contributor.person.address.postcode:: 123456
contributor.person.contact.type:: phone
contributor.person.contact.value:: 223322
contributor.role.type:: author
contributor::
contributor.organization.name.content:: Institution
contributor.role.description.content:: sponsor
contributor.role.type:: distributor
relation::
relation.type:: updates
relation.bibitem.formattedref:: ISO 19115:2003
relation::
relation.type:: obsoletes
relation.desctiption.content:: supersedes
relation.desctiption.format:: text/plain
relation.bibitem.type:: standard
relation.bibitem.formattedref:: ISO 19115:2003/Cor 1:2006
relation::
relation.type:: partOf
relation.bibitem.title.type:: main
relation.bibitem.title.content:: Book title
relation.bibitem.title.format:: text/plain
series::
series.type:: main
series.title.type:: original
series.title.content:: ISO/IEC FDIS 10118-3
series.title.language:: en
series.title.script:: Latn
series.title.format:: text/plain
series.place:: Serie's place
series.organization:: Serie's organization
series.abbreviation.content:: ABVR
series.from:: 2009-02-01
series.to:: 2010-12-20
series.number:: serie1234
series.partnumber:: part5678
series::
series.type:: alt
series.formattedref.content:: serieref
series.formattedref.language:: en
series.formattedref.script:: Latn
series.formattedref.format:: text/plain
series::
series.type:: journal
series.title.content:: Journal
series.title.format:: text/plain
series.number:: 7
series::
series.title.variant::
series.title.variant.content:: Series
series.title.variant.language:: en
series.title.variant.script:: Latn
series.title.variant::
series.title.variant.content:: Séries
series.title.variant.language:: fr
series.title.variant.script:: Latn
series.title.format:: text/plain
doctype:: document
keyword::
keyword.content:: Keyword
keyword::
keyword.content:: Key Word
editorialgroup.technical_committee.content:: Editorial group
editorialgroup.technical_committee.number:: 1
editorialgroup.technical_committee.type:: Type
ics.code:: 01
ics.text:: First
structured_identifier::
structured_identifier.docnumber:: 123
structured_identifier.agency:: agency 1
structured_identifier.agency:: agency 2
structured_identifier.type:: type 1
structured_identifier.class:: class 1
structured_identifier.partnumber:: 4
structured_identifier.edition:: 1
structured_identifier.version:: 2
structured_identifier.supplementtype:: type 2
structured_identifier.supplementnumber:: 5
structured_identifier.language:: en
structured_identifier.year:: 2020
structured_identifier::
structured_identifier.docnumber:: 456
structured_identifier.agency:: agency 3
