[%bibitem]
== {blank}
id:: ISOTC211
fetched:: 2022-05-02
title::
title.type:: title-main
title.content:: Geographic information
title.format:: text/plain
title::
title.type:: main
title.content:: Geographic information
title.format:: text/plain
title::
title.content:: Information géographique
title.language:: fr
title.script:: Latn
title.format:: text/plain
type:: standard
docid::
docid.type:: ISO
docid.primary:: true
docid.language:: en
docid.script:: Latn
docid.id:: ISO TC 211
docid::
docid.type:: isbn
docid.id:: ISBN
docid::
docid.type:: lccn
docid.id:: LCCN
docid::
docid.type:: issn
docid.scope:: series
docid.id:: ISSN
docid::
docid.type:: URN
docid.id:: urn:iso:std:iso:123:stage-90.93:ed-3:en,fr
docid:: XYZ
docid::
docid.type:: DOI
docid.id:: 10.17487/rfc1149
docid::
docid.type:: Internet-Draft
docid.id:: draft-ietf-somewg-someprotocol-07
docnumber:: TC211
edition.content:: Edition 1
edition.number:: 1.2
language:: en
language:: fr
script:: Latn
version.revision_date:: 2019-04-01
version.draft:: draft
biblionote:: note
biblionote::
biblionote.type:: annote
biblionote.content:: An note
biblionote::
biblionote.type:: howpublished
biblionote.content:: How published
biblionote::
biblionote.type:: comment
biblionote.content:: Comment
biblionote::
biblionote.type:: tableOfContents
biblionote.content:: Table Of Contents
docstatus.stage:: 30
docstatus.substage:: substage
docstatus.iteration:: final
date::
date.type:: issued
date.on:: 2014
date::
date.type:: published
date.on:: 2014-04
date::
date.type:: accessed
date.on:: 2015-05-20
abstract::
abstract.content:: <p>ISO 19115-1:2014 defines the schema required for...</p>
abstract.language:: en
abstract.script:: Latn
abstract.format:: text/html
abstract::
abstract.content:: L'ISO 19115-1:2014 définit le schéma requis pour...
abstract.language:: fr
abstract.script:: Latn
abstract.format:: text/plain
copyright.owner.name:: International Organization for Standardization
copyright.owner.abbreviation:: ISO
copyright.owner.url:: www.iso.org
copyright.role.type:: publisher
copyright.from:: 2014
copyright.to:: 2020
copyright.scope:: Scope
link::
link.type:: src
link.content:: https://www.iso.org/standard/53798.html
link.language:: en
link.script:: Latn
link::
link.type:: obp
link.content:: https://www.iso.org/obp/ui/#!iso:std:53798:en
link::
link.type:: rss
link.content:: https://www.iso.org/contents/data/standard/05/37/53798.detail.rss
link::
link.type:: doi
link.content:: http://standrd.org/doi-123
link::
link.type:: file
link.content:: file://path/file
medium.form:: medium form
medium.size:: medium size
medium.scale:: medium scale
place::
place.name:: bib place
place::
place.city:: Geneva
place.region.name:: Region
place.country.name:: Switzelznd
place.country.iso:: CH
place.country.recommended:: true
extent.locality::
extent.locality.type:: section
extent.locality.reference_from:: Reference from
extent.locality.reference_to:: Reference to
extent.locality::
extent.locality.type:: chapter
extent.locality.reference_from:: 4
extent.locality_stack::
extent.locality_stack.locality::
extent.locality_stack.locality.type:: page
extent.locality_stack.locality.reference_from:: 10
extent.locality_stack.locality.reference_to:: 20
extent.locality_stack.locality::
extent.locality_stack.locality.type:: volume
extent.locality_stack.locality.reference_from:: 1
size::
size.type:: page
size.value:: 490
size::
size.type:: plate
size.value:: 3
accesslocation:: accesslocation1
accesslocation:: accesslocation2
classification::
classification.type:: type
classification.value:: value
classification::
classification.type:: keyword
classification.value:: Keywords
classification::
classification.type:: mendeley
classification.value:: Mendeley Tags
validity.begins:: 2010-10-10 12:21
validity.ends:: 2011-02-03 18:30
validity.revision:: 2011-03-04 09:00
contributor::
contributor.organization.name:: International Organization for Standardization
contributor.organization.abbreviation:: ISO
contributor.organization.subdivision:: division
contributor.organization.url:: www.iso.org
contributor.role.description:: Publisher role
contributor.role.type:: publisher
contributor::
contributor.person.name.completename.content:: A. Bierman
contributor.person.name.completename.language:: en
contributor.person.name.completename.script:: Latn
contributor.person.affiliation.organization.name:: IETF
contributor.person.affiliation.organization.abbreviation:: IETF
contributor.person.affiliation.organization.identifier.type:: uri
contributor.person.affiliation.organization.identifier.value:: www.ietf.org
contributor.person.address.street:: Street
contributor.person.address.city:: City
contributor.person.address.state:: State
contributor.person.address.country:: Country
contributor.person.address.postcode:: 123456
contributor.person.contact.phone:: 223322
contributor.role.type:: author
contributor::
contributor.organization.name:: Institute of Electrical and Electronics Engineers
contributor.organization.abbreviation:: IEEE
contributor.organization.identifier.type:: uri
contributor.organization.identifier.value:: www.ieee.org
contributor.role::
contributor.role.description:: Publisher description
contributor.role.type:: publisher
contributor.role::
contributor.role.description:: Editor description
contributor.role.type:: editor
contributor::
contributor.person.given.forename:: Arnold
contributor.person.given.formatted-initials:: A.
contributor.person.name.surname:: Bierman
contributor.person.name.addition:: Addition
contributor.person.name.prefix:: Prefix
contributor.person.affiliation.description.content:: Description
contributor.person.affiliation.description.language:: en
contributor.person.affiliation.organization.name:: IETF
contributor.person.affiliation.organization.abbreviation:: IETF
contributor.person.type:: uri
contributor.person.value:: www.person.com
contributor.person.address.street:: Street
contributor.person.address.city:: City
contributor.person.address.state:: State
contributor.person.address.country:: Country
contributor.person.address.postcode:: 123456
contributor.person.contact.phone:: 223322
contributor.role.type:: author
contributor::
contributor.person.given.forename::
contributor.person.given.forename.content:: Arnold
contributor.person.given.forename.language:: en
contributor.person.given.forename.script:: Latn
contributor.person.given.forename.initial:: A
contributor.person.given.forename::
contributor.person.given.forename.initial:: B
contributor.person.given.formatted-initials.content:: A. B.
contributor.person.given.formatted-initials.language:: en
contributor.person.given.formatted-initials.script:: Latn
contributor.person.name.surname.content:: Bierman
contributor.person.name.surname.language:: en
contributor.person.name.surname.script:: Latn
contributor.role.type:: author
contributor::
contributor.organization.name:: World Wide Web Consortium
contributor.role.description:: sponsor
contributor.role.type:: distributor
relation::
relation.type:: updates
relation.bibitem.formattedref:: ISO 19115:2003
relation::
relation.type:: obsoletes
relation.desctiption.content:: supersedes
relation.desctiption.format:: text/plain
relation.bibitem.type:: standard
relation.bibitem.formattedref:: ISO 19115:2003/Cor 1:2006
relation::
relation.type:: partOf
relation.bibitem.title.type:: main
relation.bibitem.title.content:: Book title
relation.bibitem.title.format:: text/plain
series::
series.type:: Internet-Draft
series.title.content:: Internet-Draft
series.title.format:: text/plain
series.number:: draft-ietf-somewg-someprotocol-07
series.run:: seriesrun
series::
series.type:: main
series.title.type:: original
series.title.content:: ISO/IEC FDIS 10118-3
series.title.language:: en
series.title.script:: Latn
series.title.format:: text/plain
series.place:: Serie's place
series.organization:: Serie's organization
series.abbreviation:: ABVR
series.from:: 2009-02-01
series.to:: 2010-12-20
series.number:: serie1234
series.partnumber:: part5678
series::
series.type:: alt
series.formattedref.content:: serieref
series.formattedref.language:: en
series.formattedref.script:: Latn
series.formattedref.format:: text/plain
series.title.content:: Formattedref
series.title.format:: text/plain
series::
series.type:: journal
series.title.content:: Journal
series.title.format:: text/plain
series.number:: 7
series::
series.title.variant::
series.title.variant.content:: Series
series.title.variant.language:: en
series.title.variant.script:: Latn
series.title.variant::
series.title.variant.content:: Séries
series.title.variant.language:: fr
series.title.variant.script:: Latn
series.title.format:: text/plain
series::
series.title.content:: RFC
series.title.format:: text/plain
series.number:: 4
doctype:: document
subdoctype:: subdocument
keyword:: Keyword
keyword:: Key Word
editorialgroup.technical_committee.name:: Editorial group
editorialgroup.technical_committee.number:: 1
editorialgroup.technical_committee.type:: Type
editorialgroup.technical_committee.identifier:: Identifier
editorialgroup.technical_committee.prefix:: Prefix
ics.code:: 01
ics.text:: First
structured_identifier::
structured_identifier.docnumber:: 123
structured_identifier.agency:: agency 1
structured_identifier.agency:: agency 2
structured_identifier.type:: type 1
structured_identifier.class:: class 1
structured_identifier.partnumber:: 4
structured_identifier.edition:: 1
structured_identifier.version:: 2
structured_identifier.supplementtype:: type 2
structured_identifier.supplementnumber:: 5
structured_identifier.language:: en
structured_identifier.year:: 2020
structured_identifier::
structured_identifier.docnumber:: 456
structured_identifier.agency:: agency 3
